name: Build API docker image

on: 
  push:
    paths:
      - 'api/**'
  pull_request:
    paths:
      - 'api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and Build components 🔧
        run: |
          cd api
          npm install
          npm run lint
          npm run build
      - name: Build docker image
        if: ${{ github.ref == 'main' }}
        run: |
          docker build . -t desks-api
          docker save desks-api:latest > desk-api_latest.tar
